/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Auth': RouteRecordInfo<'/Auth', '/Auth', Record<never, never>, Record<never, never>>,
    '/AuthByEmail': RouteRecordInfo<'/AuthByEmail', '/AuthByEmail', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/LoginByEmail': RouteRecordInfo<'/LoginByEmail', '/LoginByEmail', Record<never, never>, Record<never, never>>,
    '/Main': RouteRecordInfo<'/Main', '/Main', Record<never, never>, Record<never, never>>,
    '/ServiceDetails': RouteRecordInfo<'/ServiceDetails', '/ServiceDetails', Record<never, never>, Record<never, never>>,
  }
}
