name: Deploy Prod
on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Load environment variables
        id: dotenv
        uses: falti/dotenv-action@v1
        with:
          path: /home/kdadmin/apps/admin-api/.front.env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build \
            --no-cache \
            --build-arg VITE_API_BASE_URL=${{ steps.dotenv.outputs.VITE_API_BASE_URL }} \
            -t localhost:5050/admin-api-front:main .

      - name: Push Docker Image to Local Registry
        run: |
          docker push localhost:5050/admin-api-front:main

      - name: Restart Docker Compose
        working-directory: /home/kdadmin/apps/admin-api
        run: |
          docker compose pull
          docker compose up -d
